### ISSUE TITLE
Oracle - JobStorage.Current property value has not been initialized.

### ISSUE THREAD

**Issue by s3YwCf2ZbfJG4SHAfjQMAjtsf** [xavierjefferson/Hangfire.FluentNHibernateStorage#25]
Hangfire: 1.7.28
Hangfire:FluentNHibernateStorage: 1.2.1060

There appears to be a timing issue.   When I first run my web application against an Oracle database without the Hangfire tables, if I immediately try to start a job, I get the error below.

If I restart IIS, maybe twice, eventually, everything proceeds as normal.   Please let me know if I should provide any other information from the startup steps or logs.

System.InvalidOperationException: JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.
   at Hangfire.JobStorage.get_Current()
   at Hangfire.RecurringJob.<>c.<.cctor>b__20_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()

**Comment by xavierjefferson** [comment]
This all depends on where you're placing your startup code.  Can you provider a code example?

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
Source code attached.   The Start method at line 207 is doing the startup work.

The line that fails is when we try to schedule the job at line 124.

We tried to follow your Wiki but maybe there is something we missed.   Thanks.,

[HangfireService.cs.txt](https://github.com/xavierjefferson/Hangfire.FluentNHibernateStorage/files/8921711/HangfireService.cs.txt)

**Comment by xavierjefferson** [comment]
I'd suggest moving the *RecurringJob.AddOrUpdate* call to right after the
BackgroundJobServer instance is created.   Your startup approach looks a
bit over-engineered.  Is this for a console, web, winforms, or WCF
application?  .NET Framework, Standard, or Core?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
Thanks for the direction.  Here is the information about our application.

* MVC Web App
* .Net Framework

Supposedly this line starts the backgroundJobServer: 
                _backgroundJobServer = new BackgroundJobServer(serverOptions, storage, storage.GetBackgroundProcesses());

However, I am finding that the tables don't exist.   Hence. ".Current" is not set, if try to start the job. 
If I restart IIS, then visit the site the tables are created.

For _backgroundJobServer, the "Start()" method is deprecated.

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
I noticed you and Hangfire upgraded to 1.7.30 and I gave it a try.

First web site start, fails to set the JobStorage.Current
Restart IIS - See "new set of errors"
It seems to be stuck no matter how many more times I restart IIS, same errors continue.

Previously I was using 1.2.1060 and Hangfire.Core 1.7.28, and Hangfire would at least be functional after a few IIS restarts.

New set of errors
2022-07-29 08:33:46,867 [1] ERROR NHibernate.Tool.hbm2ddl.SchemaUpdate - Unsuccessful: create index IX_Hangfire_AggregatedCounter_Key on CICOREFORCEMM."Hangfire_AggregatedCounter" ("Key")
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01408: such column list already indexed
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)
2022-07-29 08:33:46,869 [1] INFO NHibernate.Tool.hbm2ddl.SchemaUpdate - schema update complete
2022-07-29 08:33:46,951 [1] ERROR CI.HS.myMeal.Services.HangfireService - Failure starting Hangfire will try again
FluentNHibernate.Cfg.FluentConfigurationException: An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

 ---> FluentNHibernate.Cfg.FluentConfigurationException: An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

 ---> Snork.FluentNHibernateTools.SchemaException: Schema update failed with 1 exceptions.  See Exceptions property ---> Oracle.ManagedDataAccess.Client.OracleException: ORA-01408: such column list already indexed
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)
   --- End of inner exception stack trace ---
   at Snork.FluentNHibernateTools.SessionFactoryBuilder.<>c__DisplayClass7_0.<GetSessionFactoryInfo>b__0(Configuration cfg) in D:\Users\xrjef\Repos\Snork.FluentNHibernateTools\src\Snork.FluentNHibernateTools\SessionFactoryBuilder.cs:line 130
   at FluentNHibernate.Cfg.FluentConfiguration.BuildConfiguration() in /_/src/FluentNHibernate/Cfg/FluentConfiguration.cs:line 257
   --- End of inner exception stack trace ---
   at FluentNHibernate.Cfg.FluentConfiguration.BuildConfiguration() in /_/src/FluentNHibernate/Cfg/FluentConfiguration.cs:line 262
   at FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory() in /_/src/FluentNHibernate/Cfg/FluentConfiguration.cs:line 230
   --- End of inner exception stack trace ---
   at FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory() in /_/src/FluentNHibernate/Cfg/FluentConfiguration.cs:line 233
   at Snork.FluentNHibernateTools.SessionFactoryBuilder.GetSessionFactoryInfo(List`1 sourceAssemblies, FluentNHibernatePersistenceBuilderOptions options, KeyInfo keyInfo, ProviderTypeEnum providerType, Func`1 configFunc) in D:\Users\xrjef\Repos\Snork.FluentNHibernateTools\src\Snork.FluentNHibernateTools\SessionFactoryBuilder.cs:line 137
   at Snork.FluentNHibernateTools.SessionFactoryBuilder.GetFromAssemblies(List`1 sourceAssemblies, ProviderTypeEnum providerType, String nameOrConnectionString, FluentNHibernatePersistenceBuilderOptions options) in D:\Users\xrjef\Repos\Snork.FluentNHibernateTools\src\Snork.FluentNHibernateTools\SessionFactoryBuilder.cs:line 173
   at Hangfire.FluentNHibernateStorage.FluentNHibernateStorageFactory.For(ProviderTypeEnum providerType, String nameOrConnectionString, FluentNHibernateStorageOptions options)
   at CI.HS.myMeal.Services.HangfireBootstrapper.Start() in C:\Projects\CI.HS.myMeal\4.Webs\CI.HS.myMeal\Services\HangfireService.cs:line 307
   at CI.HS.myMeal.Services.HangfireService.InitializeHangfire() in C:\Projects\CI.HS.myMeal\4.Webs\CI.HS.myMeal\Services\HangfireService.cs:line 110
