### ISSUE TITLE
Oracle issue

### ISSUE THREAD

**Issue by rshivarkar** [xavierjefferson/Hangfire.FluentNHibernateStorage#3]
I configured this with oracle, I see jobs are running at pre-defined interval in sample code but I see many instances of error "-(0x80004005): ORA-08177: can't serialize access for this transaction "

Also I changed code to provide options while getting storage with with IsolationLevel.ReadCommitted

var options = new FluentNHibernateStorageOptions
                {
                    TransactionIsolationLevel = IsolationLevel.ReadCommitted,
                    QueuePollInterval = TimeSpan.FromSeconds(15),
                    JobExpirationCheckInterval = TimeSpan.FromHours(1),
                    CountersAggregateInterval = TimeSpan.FromMinutes(5),
                    PrepareSchemaIfNecessary = true,
                    DashboardJobListLimit = 50000,
                    TransactionTimeout = TimeSpan.FromMinutes(5),
                    DefaultSchema = null // use database provider's default schema
                };

 //THIS LINE GETS THE STORAGE PROVIDER
 storage = FluentNHibernateStorageFactory.For(ProviderType, connectionString, options);

Below is some part of log:
2018-09-07 15:54:46,608 [Hangfire.FluentNHibernateStorage.ExpirationManager] INFO  Hangfire.FluentNHibernateStorage.ExpirationManager [(null)] - removed records count=0
2018-09-07 15:55:02,303 [RecurringJobScheduler] INFO  Hangfire.FluentNHibernateStorage.JobQueue.FluentNHibernateJobQueue [(null)] - Enqueued JobId=14027 Queue=default
2018-09-07 15:55:04,384 [RecurringJobScheduler] INFO  Hangfire.FluentNHibernateStorage.JobQueue.FluentNHibernateJobQueue [(null)] - Enqueued JobId=14033 Queue=default
2018-09-07 15:55:11,385 [Worker #78600f25] ERROR NHibernate.AdoNet.AbstractBatcher [(null)] - Could not execute command: UPDATE "Hangfire_JobQueue" SET "FetchedAt" = :p0, "Queue" = :p1, "FetchToken" = :p2, "JobId" = :p3 WHERE "Id" = :p4
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-08177: can't serialize access for this transaction
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
2018-09-07 15:55:11,385 [Worker #6c5ffb4a] ERROR NHibernate.AdoNet.AbstractBatcher [(null)] - Could not execute command: UPDATE "Hangfire_JobQueue" SET "FetchedAt" = :p0, "Queue" = :p1, "FetchToken" = :p2, "JobId" = :p3 WHERE "Id" = :p4
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-08177: can't serialize access for this transaction
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)

**Comment by rshivarkar** [comment]
I got this working , its actually not issue , when one thread running job other thread will not get access and its as per expected

**Comment by xavierjefferson** [comment]
Updated Nuget package
